// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa8VnXFgg0SkirloHT_eC4c6MUo28ECZ0',
    appId: '1:482399216256:android:d09bd7890da86ce0b5bc65',
    messagingSenderId: '482399216256',
    projectId: 'deligo-b44e0',
    storageBucket: 'deligo-b44e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJq1mkMiI3KS4yd3zhrcN0tKaj7ikhkU',
    appId: '1:482399216256:ios:be450e3a998b9d52b5bc65',
    messagingSenderId: '482399216256',
    projectId: 'deligo-b44e0',
    storageBucket: 'deligo-b44e0.firebasestorage.app',
    androidClientId: '482399216256-l3d8hshirsg5fp2plfl8lkvkeha7s58n.apps.googleusercontent.com',
    iosClientId: '482399216256-j5ppc9an3g9q0u8s9kfrm3vni9sr77lp.apps.googleusercontent.com',
    iosBundleId: 'com.deligo.driver',
  );

}